---
stages:
  - build
  - test
  - upload

.build:
  stage: build
  tags:
   - grid5000-shell
  script:
   - /srv/ci-runner-scripts/bin/debvagrant --build
  artifacts:
    expire_in: 2 days
    paths:
      - '*.build.json'
      - '*.info'
    reports:
      junit: '*.build.junit.xml'

.test virtualbox:
  stage: test
  tags:
   - grid5000-shell
  script:
   - /srv/ci-runner-scripts/bin/debvagrant --test-virtualbox

.test libvirt:
  stage: test
  tags:
   - grid5000-shell
  script:
   - /srv/ci-runner-scripts/bin/debvagrant --test-libvirt

.upload virtualbox:
  stage: upload
  tags:
  - grid5000-shell
  only:
    refs:
      - master
  script:
  - /srv/ci-runner-scripts/bin/debvagrant --upload-virtualbox


.upload libvirt:
  stage: upload
  tags:
  - grid5000-shell
  only:
    refs:
      - master
  script:
  - /srv/ci-runner-scripts/bin/debvagrant --upload-libvirt

.upload-sandbox virtualbox:
  stage: upload
  tags:
  - grid5000-shell
  script:
  - /srv/ci-runner-scripts/bin/debvagrant --upload-sandbox-virtualbox


.upload-sandbox libvirt:
  stage: upload
  tags:
  - grid5000-shell
  script:
  - /srv/ci-runner-scripts/bin/debvagrant --upload-sandbox-libvirt
stretch-vagrant-amd64 build:
  extends: .build
  when: manual

stretch-vagrant-amd64 test-libvirt:
  extends: .test libvirt
  needs: ["stretch-vagrant-amd64 build"]

stretch-vagrant-amd64 upload-libvirt:
  extends: .upload libvirt
  needs: ["stretch-vagrant-amd64 test-libvirt"]
  when: manual

stretch-vagrant-amd64 upload-sandbox-libvirt:
  extends: .upload-sandbox libvirt
  needs: ["stretch-vagrant-amd64 test-libvirt"]
  when: manual

stretch-vagrant-amd64 test-virtualbox:
  extends: .test virtualbox
  needs: ["stretch-vagrant-amd64 build"]

stretch-vagrant-amd64 upload-virtualbox:
  extends: .upload virtualbox
  needs: ["stretch-vagrant-amd64 test-virtualbox"]
  when: manual

stretch-vagrant-amd64 upload-sandbox-virtualbox:
  extends: .upload-sandbox virtualbox
  needs: ["stretch-vagrant-amd64 test-virtualbox"]
  when: manual
stretch-vagrantcontrib-amd64 build:
  extends: .build
  when: manual

stretch-vagrantcontrib-amd64 test-libvirt:
  extends: .test libvirt
  needs: ["stretch-vagrantcontrib-amd64 build"]

stretch-vagrantcontrib-amd64 upload-libvirt:
  extends: .upload libvirt
  needs: ["stretch-vagrantcontrib-amd64 test-libvirt"]
  when: manual

stretch-vagrantcontrib-amd64 upload-sandbox-libvirt:
  extends: .upload-sandbox libvirt
  needs: ["stretch-vagrantcontrib-amd64 test-libvirt"]
  when: manual

stretch-vagrantcontrib-amd64 test-virtualbox:
  extends: .test virtualbox
  needs: ["stretch-vagrantcontrib-amd64 build"]

stretch-vagrantcontrib-amd64 upload-virtualbox:
  extends: .upload virtualbox
  needs: ["stretch-vagrantcontrib-amd64 test-virtualbox"]
  when: manual

stretch-vagrantcontrib-amd64 upload-sandbox-virtualbox:
  extends: .upload-sandbox virtualbox
  needs: ["stretch-vagrantcontrib-amd64 test-virtualbox"]
  when: manual
buster-vagrant-amd64 build:
  extends: .build

buster-vagrant-amd64 test-libvirt:
  extends: .test libvirt
  needs: ["buster-vagrant-amd64 build"]

buster-vagrant-amd64 upload-libvirt:
  extends: .upload libvirt
  needs: ["buster-vagrant-amd64 test-libvirt"]
  when: manual

buster-vagrant-amd64 upload-sandbox-libvirt:
  extends: .upload-sandbox libvirt
  needs: ["buster-vagrant-amd64 test-libvirt"]
  when: manual

buster-vagrant-amd64 test-virtualbox:
  extends: .test virtualbox
  needs: ["buster-vagrant-amd64 build"]

buster-vagrant-amd64 upload-virtualbox:
  extends: .upload virtualbox
  needs: ["buster-vagrant-amd64 test-virtualbox"]
  when: manual

buster-vagrant-amd64 upload-sandbox-virtualbox:
  extends: .upload-sandbox virtualbox
  needs: ["buster-vagrant-amd64 test-virtualbox"]
  when: manual
buster-vagrantcontrib-amd64 build:
  extends: .build

buster-vagrantcontrib-amd64 test-libvirt:
  extends: .test libvirt
  needs: ["buster-vagrantcontrib-amd64 build"]

buster-vagrantcontrib-amd64 upload-libvirt:
  extends: .upload libvirt
  needs: ["buster-vagrantcontrib-amd64 test-libvirt"]
  when: manual

buster-vagrantcontrib-amd64 upload-sandbox-libvirt:
  extends: .upload-sandbox libvirt
  needs: ["buster-vagrantcontrib-amd64 test-libvirt"]
  when: manual

buster-vagrantcontrib-amd64 test-virtualbox:
  extends: .test virtualbox
  needs: ["buster-vagrantcontrib-amd64 build"]

buster-vagrantcontrib-amd64 upload-virtualbox:
  extends: .upload virtualbox
  needs: ["buster-vagrantcontrib-amd64 test-virtualbox"]
  when: manual

buster-vagrantcontrib-amd64 upload-sandbox-virtualbox:
  extends: .upload-sandbox virtualbox
  needs: ["buster-vagrantcontrib-amd64 test-virtualbox"]
  when: manual
bullseye-vagrant-amd64 build:
  extends: .build

bullseye-vagrant-amd64 test-libvirt:
  extends: .test libvirt
  needs: ["bullseye-vagrant-amd64 build"]

bullseye-vagrant-amd64 upload-libvirt:
  extends: .upload libvirt
  needs: ["bullseye-vagrant-amd64 test-libvirt"]
  when: manual

bullseye-vagrant-amd64 upload-sandbox-libvirt:
  extends: .upload-sandbox libvirt
  needs: ["bullseye-vagrant-amd64 test-libvirt"]
  when: manual

bullseye-vagrant-amd64 test-virtualbox:
  extends: .test virtualbox
  needs: ["bullseye-vagrant-amd64 build"]

bullseye-vagrant-amd64 upload-virtualbox:
  extends: .upload virtualbox
  needs: ["bullseye-vagrant-amd64 test-virtualbox"]
  when: manual

bullseye-vagrant-amd64 upload-sandbox-virtualbox:
  extends: .upload-sandbox virtualbox
  needs: ["bullseye-vagrant-amd64 test-virtualbox"]
  when: manual
testing-vagrant-amd64 build:
  extends: .build

testing-vagrant-amd64 test-libvirt:
  extends: .test libvirt
  needs: ["testing-vagrant-amd64 build"]

testing-vagrant-amd64 upload-libvirt:
  extends: .upload libvirt
  needs: ["testing-vagrant-amd64 test-libvirt"]
  when: manual

testing-vagrant-amd64 upload-sandbox-libvirt:
  extends: .upload-sandbox libvirt
  needs: ["testing-vagrant-amd64 test-libvirt"]
  when: manual

testing-vagrant-amd64 test-virtualbox:
  extends: .test virtualbox
  needs: ["testing-vagrant-amd64 build"]

testing-vagrant-amd64 upload-virtualbox:
  extends: .upload virtualbox
  needs: ["testing-vagrant-amd64 test-virtualbox"]
  when: manual

testing-vagrant-amd64 upload-sandbox-virtualbox:
  extends: .upload-sandbox virtualbox
  needs: ["testing-vagrant-amd64 test-virtualbox"]
  when: manual
